# permissions for end users to edit kubebuildercrds.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: kubebuilder-crd
    app.kubernetes.io/managed-by: kustomize
  name: kubebuildercrd-editor-role
rules:
- apiGroups:
  - rudro.dev.rudro.dev
  resources:
  - kubebuildercrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rudro.dev.rudro.dev
  resources:
  - kubebuildercrds/status
  verbs:
  - get
