---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - rudro.dev.rudro.dev
  resources:
  - kubebuildercrds
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - rudro.dev.rudro.dev
  resources:
  - kubebuildercrds/finalizers
  verbs:
  - update
- apiGroups:
  - rudro.dev.rudro.dev
  resources:
  - kubebuildercrds/status
  verbs:
  - get
  - patch
  - update
